### PR TITLE
Polish Translation

### PR DESCRIPTION
**Pull request by anKordii**
### 😎

### CODE REVIEW

**Comment by vasilvestre** [comment]
Oh nice ! Would you please tell me the language shortcut for polish ? 
French is fr, English is en, Russian is ru... polish is po ? :D

**Comment by anKordii** [comment]
Many companies shortcut it as pl

**Comment by vasilvestre** [comment]
> Many companies shortcut it as pl
> 
> and the country domain is .pl

I will add it to the locale we handle. Thank you really much!

**Comment by vasilvestre** [comment]
🙏❤

**Pull request merged**
