### PR TITLE
Add tests to the base code

### PR DESCRIPTION
**Pull request by artandor**

### CODE REVIEW

**Comment by artandor** [comment]
The sqlite database created in the CI doesn't seem to be used by symfony, which makes the fixture load fail.

**Comment by vasilvestre** [comment]
> The sqlite database created in the CI doesn't seem to be used by symfony, which makes the fixture load fail.

It works now. But there's no fixtures

**Comment by artandor** [comment]
> > The sqlite database created in the CI doesn't seem to be used by symfony, which makes the fixture load fail.
> 
> It works now. But there's no fixtures

Nah, according to this line in the CI https://github.com/artandor/multistream-tools/runs/5444966189?check_suite_focus=true#step:9:9 the issue comes from the fact that : 

- No database is configured in the env
- Migrations are not executed

**Comment by vasilvestre** [comment]
@artandor migration are specific to either mysql or pgsql, sqlite tests should be run with doctrine:schema:update. If we want to check that migration works, we should use a real database or the docker based one

**Pull request merged**
